#!/bin/sh

url="https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/8-2018q4/gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2"

# Strip the beginning
file=${url##*/}

if [ ! -f $file ]; then
	curl -O $url
fi


echo "Extracting $file" 
tar -xf $file
dir=$(for i in gcc*; do [ -d $i ] && echo $i; done)
rm -rf $dir/share/doc

docker build -t arm-gcc-chibios . && rm -rf $dir && rm $file
